spring:
  application:
    name: library-api

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    org:
      springframework:
        security: TRACE